import { Pacifico } from "next/font/google";
import "./globals.css";
import MobilePageHeader from "./components/layout/MobilePageHeader";
import MobilePageFooter from "./components/layout/MobilePageFooter";

const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MobilePageHeader />
      <body className={`${pacifico.variable}`}>
        {children}
      </body>
      <MobilePageFooter />
    </html>
  );
}
